export const HTTP = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
};

export const ACTIVATION_STATUS = {
  GET_SMS: "get_sms",
  REFUSE: "refuse",
  USED: "used",
};

export const ACTIVATION_TYPE = {
  SMS: "SMS",
  CALL_FLASH: "CALL_FLASH",
  CALL_VOICE: "CALL_VOICE",
  CALL_INTERACTIVE: "CALL_INTERACTIVE",
  RENT_SMS: "RENT_SMS",
};
